version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: link-organizer-postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: "0114"
    ports:
      - "5435:5432" # host:container (matches application.yml: localhost:5435)
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local

