spring:
  application:
    name: LinkOrganizer

  config:
    import: optional:file:env/application-secret.yml

  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  expiration: 3600000          # 1시간 (밀리초 단위)
  refresh-token-expiration: 1209600000  # 14일 (밀리초 단위)
