CREATE TABLE accounts(
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    
    email VARCHAR(255) NOT NULL UNIQUE,
    nickname VARCHAR(255) NOT NULL,
    profile_image_url TEXT,
    provider VARCHAR(255) NOT NULL,
    provider_id VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(255) NOT NULL CHECK (role IN ('ROLE_ADMIN','ROLE_USER')),
    refresh_token TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE shared_folders (
  folder_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(100) NOT NULL,
  color      VARCHAR(20) DEFAULT '#000000',
  description  TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. 폴더 멤버 관리 테이블 (N:M 관계)
CREATE TABLE folder_members (
    folder_id BIGINT REFERENCES shared_folders(folder_id) ON DELETE CASCADE,
    account_id BIGINT REFERENCES accounts(account_id) ON DELETE CASCADE NOT NULL, 
    role VARCHAR(30) NOT NULL DEFAULT 'MEMBER' CHECK (role IN ('OWNER', 'MEMBER')),
    joined_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (folder_id, account_id) -- 한 유저는 폴더당 하나의 역할만 가짐
);

CREATE TABLE links (
  link_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id  BIGINT REFERENCES accounts(account_id) ON DELETE CASCADE,
  folder_id  BIGINT REFERENCES shared_folders(folder_id) ON DELETE CASCADE,
  url        VARCHAR(2048) NOT NULL,
  title      VARCHAR(500) NOT NULL,
  memo       TEXT,
  thumbnail_url  VARCHAR(2048), -- 미리보기 이미지 URL
  tags       TEXT[],  
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);